//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor_o_sotrudnichestve
    {
        public int ID { get; set; }
        public Nullable<int> Id_postavshic { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Postavshic Postavshic { get; set; }
    }
}
