//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_category { get; set; }
        public Nullable<int> Max_srok { get; set; }
        public Nullable<int> Min_ostatok { get; set; }
        public Nullable<int> ID_Sklad { get; set; }
        public Nullable<int> ID_kabinet { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Kabinet Kabinet { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
