//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokupka_preparat
    {
        public int ID { get; set; }
        public Nullable<int> ID_pokupka { get; set; }
        public Nullable<int> ID_preparat { get; set; }
        public Nullable<int> kolvo { get; set; }
    
        public virtual Pokupka Pokupka { get; set; }
    }
}
