//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavka_zakaz
    {
        public int ID { get; set; }
        public Nullable<int> ID_postavka { get; set; }
        public Nullable<int> ID_zakaz { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Skidka { get; set; }
    
        public virtual Postavka Postavka { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
