//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavka()
        {
            this.Postavka_zakaz = new HashSet<Postavka_zakaz>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_postavshic { get; set; }
        public Nullable<int> ID_sklad { get; set; }
        public Nullable<System.DateTime> Data_zakaz { get; set; }
        public Nullable<System.DateTime> Data_otgruzka { get; set; }
    
        public virtual Postavshic Postavshic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postavka_zakaz> Postavka_zakaz { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
