//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Priem()
        {
            this.Dogovor_na_okazanie_uslug = new HashSet<Dogovor_na_okazanie_uslug>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_specialist { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_client { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovor_na_okazanie_uslug> Dogovor_na_okazanie_uslug { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
