//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specialist()
        {
            this.Priem = new HashSet<Priem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_employee { get; set; }
        public Nullable<int> ID_kabinet { get; set; }
        public Nullable<int> ID_type { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Kabinet Kabinet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Priem> Priem { get; set; }
        public virtual Specialist_type Specialist_type { get; set; }
    }
}
